version: 2.1

executors:
  node:
    docker:
      - image: circleci/node:10.7
  api:
    docker:
      - image: circleci/node:10.7
      - image: appliedblockchain/parity-solo:latest
        auth:
          username: $DOCKER_USER
          password: $DOCKER_PASSWORD
      - image: appliedblockchain/ipfs-solo:latest
        auth:
          username: $DOCKER_USER
          password: $DOCKER_PASSWORD

jobs:
  build:
    parameters:
      directory:
        type: string
      executor:
        type: string
      script:
        type: string
      background:
        type: boolean
    executor: << parameters.executor >>

    working_directory: ~/mantle

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-<< parameters.directory >>-{{ checksum "<< parameters.directory >>/package.json" }}
          # Fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: yarn install << parameters.directory >>
          command: |
            echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/.npmrc
            cd ~/mantle/<< parameters.directory >>
            yarn install
            rm -rf ~/.npmrc

      - save_cache:
          key: v1-<< parameters.directory >>-{{ checksum "<< parameters.directory >>/package.json" }}
          paths:
            - /<< parameters.directory >>/node_modules

      - setup_remote_docker

      - run:
          name: custom command
          background: << parameters.background >>
          command: |
            cd ~/mantle/<< parameters.directory >>
            << parameters.script >>

workflows:
  version: 2
  main:
    jobs:
      - build:
          name: run_api
          directory: api
          executor: api
          script: npm run start
          background: true
      - build:
          name: test_sdk
          directory: sdk
          executor: node
          script: npm run circleci
          background: false
          requires:
            - run_api
      - build:
          name: test_api
          directory: api
          executor: node
          script: npm test
          background: false
          requires:
            - run_api
      - build:
          name: test_sdk_integration
          directory: sdk
          executor: node
          script: node bin/deployTestToken.js && source exportTestAddresses.sh && npm run circleci-integration
          background: false
          requires:
            - run_api
      - build:
          name: test_server_sdk
          directory: server-sdk
          executor: node
          script: npm test
          background: false
          requires:
            - run_api